//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiOneElearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHoi
    {
        public int ID_CauHoi { get; set; }
        public string TenCauHoi { get; set; }
        public string CauTraLoi1 { get; set; }
        public string CauTraLoi2 { get; set; }
        public string CauTraLoi3 { get; set; }
        public string CauTraLoi4 { get; set; }
        public Nullable<int> ID_BaiGiang { get; set; }
    
        public virtual BaiGiang BaiGiang { get; set; }
    }
}
