//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiOneElearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiGiang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiGiang()
        {
            this.CauHois = new HashSet<CauHoi>();
        }
    
        public int ID_BaiGiang { get; set; }
        public string TenBaiGiang { get; set; }
        public string ThoiLuong { get; set; }
        public Nullable<int> ID_ChuDe { get; set; }
        public string TaiLieuDinhKem { get; set; }
        public string Video { get; set; }
        public string NoiDungBaiGiang { get; set; }
        public Nullable<int> ID_KhoaHoc { get; set; }
    
        public virtual ChuDe ChuDe { get; set; }
        public virtual KhoaHoc KhoaHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CauHoi> CauHois { get; set; }
    }
}
